version: '3.4'

services:
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:8.0
    ports:
      - '3306:3306'
      - '33060:33060'
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: 'America/Sao_Paulo'
    networks:
      - subnet_0
    restart: on-failure
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  dotnetapi:
    container_name: dotnetapi
    hostname: dotnetapi
    image: juliocesarmidia/dotnetapi:latest
    build:
      context: ./api
    restart: on-failure
    networks:
      - subnet_0
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      ASPNETCORE_URLS: http://0.0.0.0:5000
    # volumes:
    #   - ./api:/app:rw

networks:
  subnet_0:
    driver: bridge

volumes:
  mysql-data: {}

secrets: {}
